project:
  type: website
  output-dir: docs
  # exclude by putting `_file_name.qmd` in analysis/*
# Exclude specific files or directories from the website

  render:
    # Render all .qmd files
    - "**/*.qmd"

    # Don't render anything in R/ folder (there is one *.qmd file)
    - "!R/"

execute:
  freeze: auto # Re-render only when source changes

website:
  title: "Policy lexicon"
  #description: "Instructions for R + git + AWS etc..."
  site-url: policy_lexicon.com # https://lulliter.github.io/slogan # "{{< var website.site-url >}}"
  favicon: images/notepad.png
  search: false # no magnifier on navbar
  page-navigation: true
  bread-crumbs: false # avoid the path on top of the page (sidebar!)
  page-footer:
    # left: |
    #   {{< fa regular copyright >}} Luisa M. Mimmi 2024
    left: |
      {{< fa brands creative-commons >}} 2024 [Luisa M. Mimmi](https://luisamimmi.org/) <br>
      License {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [Source code at {{< fa brands github >}}](https://github.com/Lulliter/slogan)
    background: "#e3eff7"

  navbar:
    left:
      - text: "Home"
        icon: house-fill # https://icons.getbootstrap.com/?q=home
        href: index.qmd
      # - text: "Text Analytics"
      #   icon: terminal-fill #  archive-fill # https://icons.getbootstrap.com/?q=home
      #   href: intro_NLP.qmd
      - text: "Research Plan"
        icon: clipboard-data-fill
        file: research/hypotheses.qmd
      - text: "WB case study"
        icon: globe-europe-africa #  archive-fill # https://icons.getbootstrap.com/?q=home
        menu:
          - text: "WB projects' PDO data prep"
            href: analysis/01a_WB_project_pdo_prep.qmd
          - text: "WB projects' PDO data EDA"
            href: analysis/01b_WB_project_pdo_EDA.qmd
          - text: "WB projects' PDO data ML"
            href: analysis/01c_WB_project_pdo_feat_class.qmd
      - text: "Blog"
        icon: cup-hot-fill # archive-fill # https://icons.getbootstrap.com/?q=home
        href: posts/PDO_eda.qmd

  sidebar:
    - title: "Blog posts"
      style: "docked"
      background: light
      contents:
        - posts/PDO_eda.qmd # uguale a sopra (il primo)
        - posts/blog2.qmd

format:
  html:
    theme: theme/Lulas_theme.scss # cosmo
    fontawesome: true
    css: theme/styles.css
    toc: true
    toc-location: "right"
    code-link: true
    code-fold: true
    # code-tools: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: document # margin
    footnotes-hover: true
    fontsize: 1em
    ##----- code highlighting style
    highlight-style: monokai # atom-one # github # dracula
    mainfont: "Lato"
    monofont: "Fira Mono"



