project:
  type: website
  output-dir: docs
  # exclude by putting `_file_name.qmd` in analysis/*
# Exclude specific files or directories from the website
  # render:
  #   - "!intro_NLP.qmd"

execute:
  freeze: auto

website:
  title: "slogan"
  description: "Instructions for R + git + AWS etc..."
  site-url: https://lulliter.github.io/slogan # "{{< var website.site-url >}}" # "https://lulliter.github.io/nerd-help"
  favicon: images/notepad.png
  search: false # no magnifier on navbar
  page-navigation: true
  page-footer:
    # left: |
    #   {{< fa regular copyright >}} Luisa M. Mimmi 2024
    left: |
      {{< fa brands creative-commons >}} 2024 [Luisa M. Mimmi](https://luisamimmi.org/) <br>
      License {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}} {{< fa brands creative-commons-sa >}}
      [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [Source code at {{< fa brands github >}}](https://github.com/Lulliter/slogan)
    background: "#e3eff7"

  navbar:
    left:
      - text: "Home"
        icon: house-fill # https://icons.getbootstrap.com/?q=home
        href: index.qmd
      # - text: "Text Analytics"
      #   icon: terminal-fill #  archive-fill # https://icons.getbootstrap.com/?q=home
      #   href: intro_NLP.qmd
      - text: "Research Plan"
        icon: clipboard-data-fill
        file: research/hypotheses.qmd
      - text: "WB case study"
        icon: globe-europe-africa #  archive-fill # https://icons.getbootstrap.com/?q=home
        menu:
          - text: "WB projects' PDO data prep"
            href: analysis/01a_WB_project_pdo_prep.qmd
          - text: "WB projects' PDO data EDA"
            href: analysis/01b_WB_project_pdo_EDA.qmd
          - text: "WB projects' PDO data ML"
            href: analysis/01c_WB_project_pdo_feat_class.qmd
      - text: "Blog"
        icon: cup-hot-fill # archive-fill # https://icons.getbootstrap.com/?q=home
        href: posts/PDO_eda.qmd

format:
  html:
    theme: theme/Lulas_theme.scss # cosmo
    fontawesome: true
    # css: theme/styles.css
    toc: true
    toc-location: "left"
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: document # margin
    footnotes-hover: true
    fontsize: 1em
    ##----- code highlighting style
    highlight-style: monokai # atom-one # github # dracula
    mainfont: "Lato"
    monofont: "Fira Mono"



