---
#title: "Research Plan"  # ALREADY IN YML SECTION TITLE 
# author: ""
# date: "Last run: `r format(Sys.time(), '%F')`"
lang: en
editor: source
engine: knitr
## ------  general Output Options
execute:     
  eval: false    # actually run? 
  echo: true     #  include source code in output
  warning: false  #  include warning code in output
  error: false    #  include error code in output
  output: false   # include output code in output (CHG in BLOCKS)
  # include: false   # R still runs but code and results DON"T appear in output  
  cache: false # normalmnte false
toc: true
fig-cap-location: top
tbl-cap-location: top
format:
  html:
    # theme: flatly #spacelab
    code-fold: false # redundant bc echo false 
    toc-depth: 2
    toc_float: true
    toc-location: left
    toc-title: Outline
    embed-resources: true # external dependencies embedded (Not in ..._files/)
  # pdf:
  #   toc-depth: 2
  #   toc-title: Indice
  #   highlight-style: github
  #   #lang: it
  #   embed-resources: true # external dependencies embedded (Not in ..._files/)
format-links: false
bibliography: ../bib/slogan.bib
---

# Research questions {#sec-RQ}

In general, a **research question's** nature depends on the goal and type of the pursued analysis [See fig 3.9 in @francom_introduction_2024]: 


::: {#tbl-analysis-analysis-types tbl-colwidths="[15, 19, 22, 22, 22]"}

| Type | Aims | Approach | Methods | Evaluation |
|------|------|----------|---------|------------|
| **Exploratory** | Explore: gain insight | Inductive, data-driven, and iterative | Descriptive, pattern detection with machine learning (unsupervised) | Associative |
| **Predictive** | Predict: validate associations | Semi-deductive, data-/ theory-driven, and iterative | Predictive modeling with machine learning (supervised) | Model performance, feature importance, and associative |
| **Inferential** | Explain: test hypotheses | Deductive, theory-driven, and non-iterative | Hypothesis testing with statistical tests | Causal |

Overview of analysis types
:::


### Research questions within \# 1 "EXPLORATION"

## Question 1.1 {#sec-RQ11}
***Is there a pattern in the WBG project document corpus[^1] that shows non random variation in the incidence of certain policy *concepts*[^2] over time?*** 

[^1]: *WBG project document* observed in this case are Project Development Objectives (PDO) descriptive short texts. 
[^2]: *concepts* encompasses "policy focus", "sector", "strategy" or "emerging priority" in the arena of funding for development  ....

## Question 1.2 {#sec-RQ12}
***Since the WBG project document corpus data are very incomplete when it comes to `sector` and `theme` tagging: is it possible to overcome the insufficient data completion using TOPIC MODELING?***  

## Question 1.3 {#sec-RQ13}
***Could the WDR [^3] "explain" or at least have a correlation to the appearance-prevalence of said concepts?***  

For the moment, the present study's research aim (See @tbl-analysis-analysis-types) is mainly TO **EXPLORE** (trends over time in concepts use), and possibly to **PREDICT** (conjecture about WRD traction effect).

[^3]: *WDRs* are the flagship reports of the World Bank group...


# Hypotheses

## Hyps 1.1 

The hypothesis being tested here (@sec-RQ11) is that the WBG project document corpus shows a non-random variation in the incidence of certain policy concepts over time. 

The launch of a "policy slogan" carries intrinsic motivations to shift the PDO in a certain direction. 

+ This question will be handled in a data-driven way, i.e. starting from the data and not from preconceived ideas... 
   + (i.e. I see that after 2020, the word "pandemic" and "vaccine" peaks within PDOs' texts, so I will look for a correlation with the COVID-19 pandemic shock, instead of the other way around).

## Hyps 1.2

The hypothesis being tested here (@sec-RQ12) is that some ML techniques can help improving the quality of the "document data collection", e.g. the poor and incomplete sector/theme tagging of the WBG project documents.

+ Note that for this purpose the available dataset (~ 20 FYs worth of project PDOs descriptions) has been splitted into a training + validation + test sets.  

## Hyps 1.3
The "alternative" hypothesis being tested here (@sec-RQ13) is that the WDR has a "traction effect" on the PDO of the following FYs.
 
___ 

# Possible (interesting) follow-up
### Research questions within \# 2 "EXPLANATION "why""

The important question is ***"WHY" does such a deviation from the original meaning of a word/sentence occur?***. Granted, languages evolve on their own, but it can also be subject to manipulation, as George Orwell's "1984" so powerfully depicted illustrating the rules and purpose of fictional Oceania nation's *newspeak*. The risks connected to this potential abuse of language are clearly laid out by Riccardo Garbini in his "Lessico - Uscire da Babele" [@garbini_uscire_2003, p.4] [^4]\
<!-- > In alcuni casi la deviazione del significato si evidenzia mediante la soppressione pura e semplice del termine (1984): in tali casi dunque l'analisi non insiste sull'aspetto riduzionista. Le deviazioni, laddove presenti, sono dettate soprattutto da intenti ideologici, ossia dalla sovrapposizione di una griglia interpretativa con maglie piuttosto rigide sui dati oggettivi della realtà. L'effetto della sovrapposizione di questa griglia interpretativa chiamata ideologia risulta in tal modo una riduzione del campo percettivo ed interpretativo della realtà. Per questa ragione le deviazioni semantiche sono state denominate 'riduzionismi'.  -->

[^4]: Annex to the Giuseppe Fioravanti's book [@fioravanti_pedagogia_2006]

> *In some cases the deviation of the meaning is evidenced by the pure and simple suppression of the term (1984): in such cases, therefore, the analysis does not insist on the reductionist aspect. **The deviations, where present, are dictated above all by ideological intentions, that is, by the superimposition of an interpretative grid with rather rigid meshes on the objective data of reality.** The effect of the superimposition of this interpretative grid called ideology thus results in a reduction of the perceptive and interpretative field of reality. For this reason semantic deviations have been called 'reductionisms'.*

### Research questions within \# 3 "EXPLANATION: "how""

Assuming that we may, at least, form hypotheses on why this "reduction" occurs, **"HOW does the the deviation from reality (in the language common use) sparkle and then spread?"** Can we detect the mechanisms? 

### Research question's area \# 4 "WHAT CONSEQUENCES" 

Besides investigating the origin, it would be equally important to ***understand the consequences of a lamented lessical approximation or reduction***.


